name: link-check

on:
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest
    env:
      DOWNLOAD_URL: https://www.fellowus.com/download
    strategy:
      matrix:
        target:
          - "README.md"
          - "docs/**/*.md"
          - "docs/**"
          - "src/**/*.mdx"
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config .lychee.toml --no-progress --verbose ${{ matrix.target }}
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report-${{ matrix.target }}
          path: lychee/out.md
          if-no-files-found: warn
